[dependencies]
rand = "https://github.com/aviate-labs/rand.mo#v0.2.3"
ulid = "https://github.com/aviate-labs/ulid.mo#v0.1.3"
map = "https://github.com/ZhenyaUsenko/motoko-hash-map#v9.0.1"
alfangodb = "https://github.com/megalinker/alfangodb/tree/db-additions"
d3storage = "https://github.com/megalinker/d3storage/tree/master"
httpParser = "https://github.com/NatLabs/http-parser.mo#v0.1.2"
canistergeek = "0.0.8"
serde = "2.1.2"
time-consts = "1.0.1"
datetime = "0.1.3"
stableheapbtreemap = "1.5.0"
vector = "0.4.1"
base = "0.14.0"
